name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  validate-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Check changelog entry
      uses: actions/github-script@v7
      with:
        script: |
          const prBody = context.payload.pull_request.body || '';
          const sections = ['Added', 'Changed', 'Fixed', 'Security'];
          
          let hasChangelogEntry = false;
          
          for (const section of sections) {
            const regex = new RegExp(`### ${section}\\s*\\n([\\s\\S]*?)(?=### |$)`, 'i');
            const match = prBody.match(regex);
            
            if (match && match[1]) {
            const content = match[1].trim();
            // Check if section has actual content (not just empty bullet points)
            const hasContent = content && content !== '-' && !/^-\s*$/.test(content);
            if (hasContent) {
              hasChangelogEntry = true;
              break;
            }
          }
          
          if (!hasChangelogEntry) {
            core.setFailed('Please provide a changelog entry in the PR description');
          }