
name: PR Description Validator

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-description:
    name: Validate PR Description
    runs-on: ubuntu-latest
    steps:
    - name: Set up workspace
      uses: actions/checkout@v2

    - name: Validate PR Description
      run: |
        # Ensure jq is installed
        sudo apt-get install jq

        # Fetch PR description using jq
        PR_DESCRIPTION=$(jq -r ".pull_request.body" "$GITHUB_EVENT_PATH")

        echo "PR Description: $PR_DESCRIPTION"

        # KEYWORD="REQUIRED_KEYWORD"

        # # Check for the required keyword in the PR description
        # if [[ $PR_DESCRIPTION != *"$KEYWORD"* ]]; then
        #   echo "PR description does not contain the required keyword."
        #   exit 1
        # fi